load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "stm32f3discovery",
    hdrs = [
        "board.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//bsp/pin",
    ],
)
