load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "utility",
    srcs = [
        "utility.cpp",
        "utility.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@stm32f3xx_hal",
    ],
)
